const weatherCode = [
  {
    code: 0,
    label: "Soleil",
    text: "Ensoleillé",
    weatherIsGood: true,
    icon: "./assets/icon_Sun.svg",
    urlbg: "./assets/sun.jpg",
  },
  {
    code: 1,
    label: "Peu nuageux",
    text: "Partiellement Ensoleillé",
    weatherIsGood: true,
    icon: "./assets/icon_Partly_Cloudy.svg",
    urlbg: "./assets/cloudy-sun.jpg",
  },
  {
    code: 2,
    label: "Ciel voilé",
    text: "Partiellement Ensoleillé",
    weatherIsGood: true,
    icon: "./assets/icon_Partly_Cloudy.svg",
    urlbg: "./assets/cloudy-sun.jpg",
  },
  {
    code: 3,
    label: "Nuageux",
    text: "Nuageux",
    weatherIsGood: true,
    icon: "./assets/icon_Cloudy.svg",
    urlbg: "./assets/cloudy.jpg",
  },
  {
    code: 4,
    label: "Très nuageux",
    text: "Nuageux",
    weatherIsGood: true,
    icon: "./assets/icon_Cloudy.svg",
    urlbg: "./assets/cloudy.jpg",
  },
  {
    code: 5,
    label: "Couvert",
    text: "Nuageux",
    weatherIsGood: true,
    icon: "./assets/icon_Cloudy.svg",
    urlbg: "./assets/cloudy.jpg",
  },
  {
    code: 6,
    label: "Brouillard",
    text: "Nuageux",
    weatherIsGood: true,
    icon: "./assets/icon_Cloudy.svg",
    urlbg: "./assets/cloudy.jpg",
  },
  {
    code: 7,
    label: "Brouillard givrant",
    text: "Nuageux",
    weatherIsGood: true,
    icon: "./assets/icon_Cloudy.svg",
    urlbg: "./assets/cloudy.jpg",
  },
  {
    code: 10,
    label: "Pluie faible",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 11,
    label: "Pluie modérée",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 12,
    label: "Pluie forte",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 13,
    label: "Pluie faible verglaçante",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 14,
    label: "Pluie modérée verglaçante",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 15,
    label: "Pluie forte verglaçante",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 16,
    label: "Bruine",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 20,
    label: "Neige faible",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 21,
    label: "Neige modérée",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 22,
    label: "Neige forte",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 30,
    label: "Pluie et neige mêlées faibles",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 31,
    label: "Pluie et neige mêlées modérées",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 32,
    label: "Pluie et neige mêlées fortes",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 40,
    label: "Averses de pluie locales et faibles",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 41,
    label: "Averses de pluie locales",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 42,
    label: "Averses locales et fortes",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 43,
    label: "Averses de pluie faibles",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 44,
    label: "Averses de pluie",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 45,
    label: "Averses de pluie fortes",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 46,
    label: "Averses de pluie faibles et fréquentes",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 47,
    label: "Averses de pluie fréquentes",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 48,
    label: "Averses de pluie fortes et fréquentes",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 60,
    label: "Averses de neige localisées et faibles",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 61,
    label: "Averses de neige localisées",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 62,
    label: "Averses de neige localisées et fortes",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 63,
    label: "Averses de neige faibles",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 64,
    label: "Averses de neige",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 65,
    label: "Averses de neige fortes",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 66,
    label: "Averses de neige faibles et fréquentes",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 67,
    label: "Averses de neige fréquentes",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 68,
    label: "Averses de neige fortes et fréquentes",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 70,
    label: "Averses de pluie et neige mêlées localisées et faibles",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 71,
    label: "Averses de pluie et neige mêlées localisées",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 72,
    label: "Averses de pluie et neige mêlées localisées et fortes",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 73,
    label: "Averses de pluie et neige mêlées faibles",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 74,
    label: "Averses de pluie et neige mêlées",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 75,
    label: "Averses de pluie et neige mêlées fortes",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 76,
    label: "Averses de pluie et neige mêlées faibles et nombreuses",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 77,
    label: "Averses de pluie et neige mêlées fréquentes",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 78,
    label: "Averses de pluie et neige mêlées fortes et fréquentes",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 100,
    label: "Orages faibles et locaux",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 101,
    label: "Orages locaux",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 102,
    label: "Orages fort et locaux",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 103,
    label: "Orages faibles",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 104,
    label: "Orages",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 105,
    label: "Orages forts",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 106,
    label: "Orages faibles et fréquents",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 107,
    label: "Orages fréquents",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 108,
    label: "Orages forts et fréquents",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 120,
    label: "Orages faibles et locaux de neige ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 121,
    label: "Orages locaux de neige ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 122,
    label: "Orages forts et locaux de neige ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 123,
    label: "Orages faibles de neige ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 124,
    label: "Orages de neige ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 125,
    label: "Orages forts de neige ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 126,
    label: "Orages faibles et fréquents de neige ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 127,
    label: "Orages fréquents de neige ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 128,
    label: "Orages forts et fréquents de neige ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 130,
    label: "Orages faibles et locaux de pluie et neige mêlées ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 131,
    label: "Orages locaux de pluie et neige mêlées ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 132,
    label: "Orages forts et locaux de pluie et neige mêlées ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 133,
    label: "Orages faibles de pluie et neige mêlées ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 134,
    label: "Orages de pluie et neige mêlées ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 135,
    label: "Orages forts de pluie et neige mêlées ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 136,
    label: "Orages faibles et fréquents de pluie et neige mêlées ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 137,
    label: "Orages fréquents de pluie et neige mêlées ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 138,
    label: "Orages forts et fréquents de pluie et neige mêlées ou grésil",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 140,
    label: "Pluies orageuses",
    text: "Orageux",
    weatherIsGood: false,
    icon: "./assets/icon_Thunderstorm.svg",
    urlbg: "./assets/storm.jpg",
  },
  {
    code: 141,
    label: "Pluie et neige mêlées à caractère orageux",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 142,
    label: "Neige à caractère orageux",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 210,
    label: "Pluie faible intermittente",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 211,
    label: "Pluie modérée intermittente",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 212,
    label: "Pluie forte intermittente",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 220,
    label: "Neige faible intermittente",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 221,
    label: "Neige modérée intermittente",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 222,
    label: "Neige forte intermittente",
    text: "Neige",
    weatherIsGood: false,
    icon: "./assets/icon_Snow.svg",
    urlbg: "./assets/snow.jpg",
  },
  {
    code: 230,
    label: "Pluie et neige mêlées",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 231,
    label: "Pluie et neige mêlées",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 232,
    label: "Pluie et neige mêlées",
    text: "Pluvieux",
    weatherIsGood: false,
    icon: "./assets/icon_Rain.svg",
    urlbg: "./assets/rain.jpg",
  },
  {
    code: 235,
    label: "Averses de grêle",
    text: "Grêle",
    weatherIsGood: false,
    icon: "./assets/icon_Hail.svg",
    urlbg: "./assets/hail.jpg",
  },
];

export default weatherCode;
